name: CI -> Deploy to My website

on:
  push:
    branches: [main]

jobs:
  deploy-static:
    runs-on: ubuntu-latest
    environment:
      name: redc

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: FTP Deployment
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: ${{ secrets.FTP_LOCAL_DIR}}
          remote_dir: ${{ secrets.FTP_REMOTE_DIR}}
          delete: "false"

          # Você pode adicionar mais opções conforme necessário
